### ISSUE TITLE
error for env setup:ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query'

### ISSUE THREAD

**Issue by JerryX1110** [zhyever/SimIPU#6]
Thanks for your insightful paper and clear code repo!

Hi, I met with the **ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query'** when run the command bash tools/dist_train.sh project_cl/configs/simipu/simipu_kitti.py 1 --work_dir ./ 

Do you know how to solve it?

Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmdet3d.apis import train_model
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/core/bbox/__init__.py", line 4, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/core/bbox/iou_calculators/__init__.py", line 1, in <module>
    from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 5, in <module>
    from ..structures import get_box_type
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/core/bbox/structures/__init__.py", line 1, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
    from .ball_query import ball_query
  File "/mnt/lustre/xxh/SimIPU-main/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query' (/mnt/lustre/xxh/SimIPU-main/mmdet3d/ops/ball_query/__init__.py)

I noticed that you once met with the same error.
https://github.com/open-mmlab/mmdetection3d/issues/503#issuecomment-847618114

So, I would like to ask for your help~ Hopefully you have a good solution. :)

**Comment by zhyever** [comment]
Sorry, I forget the specific solution. But why not try to build the simipu(mmdet3d) following the https://github.com/open-mmlab/mmdetection3d/issues/503#issuecomment-847726732. It is possible that you forget to build the codes.

**Comment by JerryX1110** [comment]
I've solved the problem. Thanks~
